import fs from 'node:fs';
import * as XLSX from 'xlsx';

import { test, expect } from './fixtures';
import { NAV_ORIGIN } from '../../scripts/browser-smoke-config.mjs';

function workbookRows(downloadPath: string, sheetName: string) {
  const workbook = XLSX.readFile(downloadPath);
  expect(workbook.SheetNames).toEqual([sheetName]);
  return XLSX.utils.sheet_to_json<Record<string, string | number>>(
    workbook.Sheets[sheetName],
    { range: 2 },
  );
}

test('Certificates exports the visible audit history as a real Excel download', async ({ page }) => {
  await page.goto(`${NAV_ORIGIN}/admin-certificates`);
  await expect(page.getByRole('heading', { name: 'Certificate History' })).toBeVisible();
  await expect(page.getByText('JS-AIK-2026-0001', { exact: true })).toBeVisible();

  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export Excel' }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe('Certificate-History.xlsx');
  const downloadPath = await download.path();
  expect(downloadPath).not.toBeNull();
  expect(fs.statSync(downloadPath!).size).toBeGreaterThan(1_000);

  const rows = workbookRows(downloadPath!, 'Certificates');
  expect(rows).toHaveLength(1);
  expect(rows[0]).toMatchObject({
    'Certificate Number': 'JS-AIK-2026-0001',
    'Member ID': 'JS0001',
    'Aikikai Registration Number': 'A12345',
    'Member Name': 'Fixture Member',
    Class: 'Aikido',
    Status: 'Valid',
    'Total Prints': 1,
  });
});

test('Reports exports the visible official report history as a real Excel download', async ({ page }) => {
  await page.goto(`${NAV_ORIGIN}/admin-reports`);
  await expect(page.getByRole('heading', { name: 'Official Report History' })).toBeVisible();
  await expect(page.getByText('JS-REPORT-2026-0001', { exact: true })).toBeVisible();

  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export Excel' }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe('Official-Report-History.xlsx');
  const downloadPath = await download.path();
  expect(downloadPath).not.toBeNull();
  expect(fs.statSync(downloadPath!).size).toBeGreaterThan(1_000);

  const rows = workbookRows(downloadPath!, 'Report History');
  expect(rows).toHaveLength(1);
  expect(rows[0]).toMatchObject({
    'Document Reference': 'JS-REPORT-2026-0001',
    'Member ID': 'JS0001',
    'Member Name': 'Fixture Member',
    Class: 'Aikido',
    'Report Type': 'Official Member Record',
    'Generated By': 'Fixture Administrator',
    'Generator Role': 'super_admin',
  });
});

test('Archive remains view-only and exposes its complete record without a download action', async ({ page }) => {
  await page.goto(`${NAV_ORIGIN}/admin-archive`);
  await expect(page.getByRole('heading', { name: 'Archive', exact: true })).toBeVisible();
  await expect(page.getByText('JS-AIK-2026-0001', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: /export|download/i })).toHaveCount(0);

  await page.getByRole('button', { name: 'View Record' }).evaluate(button => (button as HTMLButtonElement).click());
  const dialog = page.getByRole('dialog');
  await expect(dialog).toContainText('View only');
  await expect(dialog).toContainText('Fixture Member');
  await expect(dialog).toContainText('A12345');
  await expect(dialog.getByRole('button', { name: /export|download/i })).toHaveCount(0);
});
