import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const verificationPage = await readFile(
  new URL("../app/certificate/verify/[certificateId]/page.tsx", import.meta.url),
  "utf8",
);
const assessmentPage = await readFile(
  new URL("../app/admin/assessments/page.tsx", import.meta.url),
  "utf8",
);
const certificatePdf = await readFile(
  new URL("../components/GradeCertificatePDF.tsx", import.meta.url),
  "utf8",
);
const migration = await readFile(
  new URL("../supabase/migrations/042_prepare_assessment_certificates.sql", import.meta.url),
  "utf8",
);

test("QR payload carries the requested facts and a database verification URL", () => {
  for (const field of ["name=", "rank=", "date=", "assessor=", "verify="]) {
    assert.match(assessmentPage, new RegExp(`encodeURIComponent\\(.*${field}|${field}`, "i"));
  }
  assert.match(assessmentPage, /QRCode\.toDataURL\(barcodePayload/i);
  assert.match(certificatePdf, /verificationBarcodeUrl[\s\S]*SCAN TO VERIFY AUTHENTICITY/i);
  assert.match(
    certificatePdf,
    /JINGWUGUAN SEIBUKAN[\s\S]*record\.class_name\.toUpperCase\(\)[\s\S]*CERTIFICATE OF PROMOTION/i,
  );
});

test("printed certificate has only the authorized-signatory signature line", () => {
  assert.equal([...certificatePdf.matchAll(/styles\.signatureLine/g)].length, 1);
  assert.match(certificatePdf, /Authorized Signatory[\s\S]*Jingwuguan Seibukan Head/);
  assert.doesNotMatch(certificatePdf, /\{assessorName\}/);
});

test("promotion certificate has only the requested ordered details and no generator footer", () => {
  const details = certificatePdf.match(/<View style=\{styles\.details\}>([\s\S]*?)\{\/\*[\s\S]*?REPRINT NOTICE/)?.[1];
  assert.ok(details);
  assert.deepEqual([...details.matchAll(/<Text style=\{styles\.label\}>(.*?)<\/Text>/g)].map(match => match[1]), [
    "Member ID", "Promotion Date", "Certificate No.",
  ]);
  assert.match(details, /record\.member_id/);
  assert.doesNotMatch(details, /aikikai|Discipline|Dojo|Grading Assessor|Print Type/);
  assert.doesNotMatch(certificatePdf, /Generated by|audit\.generated_at|audit\.generated_by_name|styles\.footer/);
  // Metadata remains available for callers and their persisted print history.
  assert.match(certificatePdf, /export type CertificateAudit[\s\S]*generated_at: string/);
  assert.match(certificatePdf, /OFFICIAL REPRINT - ORIGINAL CERTIFICATE NUMBER RETAINED/);
});

test("public scan page validates through a server-only RPC without offering a document", () => {
  assert.match(verificationPage, /createAdminClient\(\)/i);
  assert.match(verificationPage, /verify_prepared_assessment_certificate/i);
  assert.match(verificationPage, /ISSUED - VALID/i);
  assert.match(verificationPage, /VOID - NOT VALID/i);
  assert.match(verificationPage, /PENDING - NOT YET VALID/i);
  assert.match(verificationPage, /does not provide a certificate download/i);
  assert.doesNotMatch(verificationPage, /<a\b|href=|\.pdf\b/i);
});

test("members cannot read or execute the prepared-certificate storage boundary", () => {
  assert.match(
    migration,
    /revoke all on table public\.prepared_assessments,[\s\S]*public\.prepared_assessment_candidates,[\s\S]*public\.prepared_assessment_certificates[\s\S]*from public, anon, authenticated/i,
  );
  assert.match(migration, /Only an active Super Admin can print prepared certificates/i);
  assert.match(migration, /verify_prepared_assessment_certificate\(uuid\)[\s\S]*to service_role/i);
});
